[package]
name = "rust-web-server"
version = "0.1.0"
edition = "2021"
authors = ["James Dean (james.kademlia@gmail.com)"]

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
